### ISSUE TITLE
多语言列表不受 erupt 参数控制

### ISSUE THREAD

**Issue by supercat188** [erupts/erupt-web#53]
### 版本情况
erupt-web 版本： 1.12.3 （请确保最新尝试是否还有问题）

### 问题描述（包括截图）
多语言列表不受 erupt 参数控制
erupt-app:
  # 多语言配置，默认支持：简体中文、繁体中文、英文、日文；具体配置详见erupt-i18n模块
  locales: [ "zh-CN","zh-TW","en-US"]

**Comment by erupts** [comment]
升级版本至1.12.7 即可解决该配置不生效的问题
