### ISSUE TITLE
1.12以上版本, ckeditor.js丢失

### ISSUE THREAD

**Issue by fawn-deer** [erupts/erupt-web#64]
### 版本情况
erupt-web 版本： 1.12版本以上

### 问题描述（包括截图）
1.12版本移除了 `src/assets/js/ckeditor.js`, 导致无法直接使用ck编辑器

### 临时解决办法
自行添加 `/assets/js/ckeditor.js` 文件映射, 例如在nginx中添加映射

```
location /assets/js/ckeditor.js {
        alias /static/assets/js/ckeditor.js;
    }
```

**Comment by erupts** [comment]
1.12.12 版本已修复此问题
